openapi: "3.1.0"

info:
  title: Pushpad API
  version: "1.0"
  description: |
    The Pushpad API allows you to send web push notifications and manage resources
    within your Pushpad account in a simple way using HTTP requests.
    All of the functionality that you are familiar with in the Pushpad
    dashboard is also available through the API.
  license:
    name: Apache 2.0
    url: "https://opensource.org/license/apache-2-0"
  contact:
    name: Pushpad Support
    email: support@pushpad.xyz
  termsOfService: "https://pushpad.xyz/tos"

servers:
  - url: "https://pushpad.xyz/api/v1"
    description: production
    
components:
  securitySchemes:
    TokenAuth:
      type: http
      scheme: Token
      description: |
        Authentication with access token (API key).

        Example header:
        `Authorization: Token token="YOUR_ACCESS_TOKEN"`

security:
  - TokenAuth: []

tags:
  - name: Notifications
    description: |
      A notification is a web push notification sent with Pushpad.
      
      By sending requests to the Notifications endpoint, you can
      create, read or delete notifications.

  - name: Subscriptions
    description: |
      A subscription is a subscription to notifications.
      
      By sending requests to the Subscriptions endpoint, you can
      create, read, update or delete subscriptions.

  - name: Projects
    description: |
      A project is a project on Pushpad.
      
      By sending requests to the Projects endpoint, you can
      create, read, update or delete projects.

  - name: Senders
    description: |
      A sender is the owner of the subscriptions and signer of the notifications.
      
      By sending requests to the Senders endpoint, you can
      create, read, update or delete senders.

paths:
  /projects/{project_id}/notifications:
    get:
      $ref: "resources/notifications/notifications_list.yml"
    post:
      $ref: "resources/notifications/notifications_create.yml"
  /notifications/{notification_id}:
    get:
      $ref: "resources/notifications/notifications_get.yml"
  /notifications/{notification_id}/cancel:
    delete:
      $ref: "resources/notifications/notifications_cancel.yml"

  /projects/{project_id}/subscriptions:
    get:
      $ref: "resources/subscriptions/subscriptions_list.yml"
    post:
      $ref: "resources/subscriptions/subscriptions_create.yml"
  /projects/{project_id}/subscriptions/{subscription_id}:
    get:
      $ref: "resources/subscriptions/subscriptions_get.yml"
    patch:
      $ref: "resources/subscriptions/subscriptions_update.yml"
    delete:
      $ref: "resources/subscriptions/subscriptions_delete.yml"
  
  /projects:
    get:
      $ref: "resources/projects/projects_list.yml"
    post:
      $ref: "resources/projects/projects_create.yml"
  /projects/{project_id}:
    get:
      $ref: "resources/projects/projects_get.yml"
    patch:
      $ref: "resources/projects/projects_update.yml"
    delete:
      $ref: "resources/projects/projects_delete.yml"

  /senders:
    get:
      $ref: "resources/senders/senders_list.yml"
    post:
      $ref: "resources/senders/senders_create.yml"
  /senders/{sender_id}:
    get:
      $ref: "resources/senders/senders_get.yml"
    patch:
      $ref: "resources/senders/senders_update.yml"
    delete:
      $ref: "resources/senders/senders_delete.yml"
